### ISSUE TITLE
[Solved] Language file /resources/us.properties doesn't exist or isn't readable

### ISSUE THREAD

**Issue by godfuzz3r** [mame82/duckencoder.py#3]
Language file /resources/us.properties doesn't exist or isn't readable
How to solve this problem?

**Comment by mame82** [comment]
Are you sure you cloned recursively?

What is the content of /home/pi/P4wnP1/duckencoder/resources ?

**Comment by mame82** [comment]
Forget the last comment... wrong project

**Comment by mame82** [comment]
How did you produce this error?

**Comment by godfuzz3r** [comment]
I did this:
1. Clone duckencoder: 
  git clone https://github.com/mame82/duckencoder.py.git
2. In duckencoder directory create duck-payload:
  echo "STRING test" > test.duck
3. Run the script:
  python duckencoder.py -i test.duck -o test.bin -l us
4. Got a problem:
  Language file /resources/us.properties doesn't exist or isn't readable

5. cd resources
6. ls -l
-rwxr-xr-x 1 lafa lafa 4560 авг 27 23:03 be.properties
-rwxr-xr-x 1 lafa lafa 3494 авг 27 23:03 br.properties
-rwxr-xr-x 1 lafa lafa 5756 авг 27 23:03 ca.properties
-rwxr-xr-x 1 lafa lafa 7291 авг 27 23:03 ch.properties
-rwxr-xr-x 1 lafa lafa 7070 авг 27 23:03 de.properties
-rwxr-xr-x 1 lafa lafa 8704 авг 27 23:03 dk.properties
-rwxr-xr-x 1 lafa lafa 4108 авг 27 23:03 es.properties
-rwxr-xr-x 1 lafa lafa 3331 авг 27 23:03 fi.properties
-rwxr-xr-x 1 lafa lafa 4825 авг 27 23:03 fr.properties
-rwxr-xr-x 1 lafa lafa 4664 авг 27 23:03 gb.properties
-rwxr-xr-x 1 lafa lafa 4424 авг 27 23:03 hr.properties
-rwxr-xr-x 1 lafa lafa 3927 авг 27 23:03 it.properties
-rwxr-xr-x 1 lafa lafa 2377 авг 27 23:03 keyboard.properties
-rwxr-xr-x 1 lafa lafa 8778 авг 27 23:03 no.properties
-rwxr-xr-x 1 lafa lafa 4857 авг 27 23:03 pt.properties
-rwxr-xr-x 1 lafa lafa 7068 авг 27 23:03 ru.properties
-rwxr-xr-x 1 lafa lafa 4473 авг 27 23:03 si.properties
-rwxr-xr-x 1 lafa lafa 8459 авг 27 23:03 sv.properties
-rwxr-xr-x 1 lafa lafa 3993 авг 27 23:03 tr.properties
-rwxr-xr-x 1 lafa lafa 3860 авг 27 23:03 us.properties

**Comment by godfuzz3r** [comment]
Sorry for the long-time answer

**Comment by mame82** [comment]
Can see the issue, needs to be fixed.

Quick and dirry solution: run duckencoder from a different directory, like `cd ..` 
`python ./duckencoder.py -i ./duckencoder.py/test.duck -o  test.bin -l us`

Hope this works meanwhile, need some time to revisit this project and solve the issues (incorrect working dir detection in this case)

**Comment by mame82** [comment]
Excuse the late reply, should be fixed
